import type { Widen } from '@/core/dict'
import type { Locale } from '@/types'

const EN = {
  appName: 'VibeCheck',
  emptyTitle: 'No feedback yet',
  emptyBody: 'Press {shortcut} on a page, then S to select an area or C to leave a comment.',
  shortcutMissing: 'No keyboard shortcut is assigned',
  shortcutFix: 'Set the keyboard shortcut',
  newSession: 'New review',
  deleteSession: 'Delete this review',
  sessions: 'Reviews',
  settings: 'Settings',
  background: 'Background',
  request: 'Requested change',
  backgroundPlaceholder: 'What you noticed, and the situation',
  requestPlaceholder: 'What should change',
  selectAll: 'Select all',
  selected: (n: number) => `${n} selected`,
  copy: 'Copy',
  copySheet: 'Numbered image',
  copyMarkdown: 'Markdown (saves images, links by path)',
  copyText: 'Text only',
  save: 'Save',
  issue: 'Issue',
  slack: 'Slack',
  discord: 'Discord',
  delete: 'Delete',
  moveUp: 'Move up',
  moveDown: 'Move down',
  open: 'Open page',
  working: 'Working…',
  copiedSheet: 'Copied the numbered image',
  copiedText: 'Copied',
  savedTo: (folder: string) => `Saved to ${folder}`,
  postedSlack: 'Posted to Slack',
  postedDiscord: 'Posted to Discord',
  issueCreated: (n: number) => `Created issue #${n}`,
  nothingSelected: 'Select at least one item',
  needsGithub: 'Connect GitHub first',
  needsSlack: 'Set up Slack first',
  needsDiscord: 'Add a Discord webhook first',
  openSettings: 'Open settings',
  chooseRepo: 'Repository',
  chooseChannel: 'Channel',
  chooseWebhook: 'Webhook',
  send: 'Send',
  cancel: 'Cancel',
  privateRepoNotice:
    'This repository is private, so screenshots become links. The numbered image is copied afterwards — paste it into the issue.',
  pasteAfterIssue: 'Numbered image copied — paste it into the issue.',
} as const

export type PanelStrings = Widen<typeof EN>

const JA: PanelStrings = {
  appName: 'VibeCheck',
  emptyTitle: '指摘はまだありません',
  emptyBody: 'ページで {shortcut} を押し、S で範囲を選択、C でコメントだけ残せます。',
  shortcutMissing: 'ショートカットが未割り当てです',
  shortcutFix: 'キーボードショートカットを設定',
  newSession: '新しいレビュー',
  deleteSession: 'このレビューを削除',
  sessions: 'レビュー',
  settings: '設定',
  background: '背景',
  request: 'アップデート内容',
  backgroundPlaceholder: 'なぜ気づいたか / どういう状況か',
  requestPlaceholder: 'どう変えてほしいか',
  selectAll: 'すべて選択',
  selected: (n: number) => `${n}件選択中`,
  copy: 'コピー',
  copySheet: '合成画像（番号つき）',
  copyMarkdown: 'Markdown（画像を保存してパス付き）',
  copyText: 'テキストのみ',
  save: '保存',
  issue: 'Issue',
  slack: 'Slack',
  discord: 'Discord',
  delete: '削除',
  moveUp: '上へ',
  moveDown: '下へ',
  open: 'ページを開く',
  // status
  working: '処理中…',
  copiedSheet: '合成画像をコピーしました',
  copiedText: 'コピーしました',
  savedTo: (folder: string) => `${folder} に保存しました`,
  postedSlack: 'Slack に投稿しました',
  postedDiscord: 'Discord に投稿しました',
  issueCreated: (n: number) => `Issue #${n} を作成しました`,
  nothingSelected: '指摘を選択してください',
  needsGithub: 'GitHub と接続してください',
  needsSlack: 'Slack の設定が必要です',
  needsDiscord: 'Discord Webhook を登録してください',
  openSettings: '設定を開く',
  // destination pickers
  chooseRepo: 'リポジトリ',
  chooseChannel: 'チャンネル',
  chooseWebhook: 'Webhook',
  send: '送信',
  cancel: 'キャンセル',
  privateRepoNotice:
    'private リポジトリのため画像はリンクになります。作成後に合成画像をコピーするので、Issue に貼り付けてください。',
  pasteAfterIssue: '合成画像をコピーしました。Issue に貼り付けてください。',
}

export const PANEL_STRINGS: Record<Locale, PanelStrings> = { en: EN, ja: JA }

export function panelStrings(locale: Locale): PanelStrings {
  return PANEL_STRINGS[locale]
}
