import type { Widen } from './dict'
import type { Locale } from '@/types'

/** Every user-visible string that ships in exported artefacts lives here. */
const EN = {
  background: 'Background',
  request: 'Requested change',
  page: 'Page',
  element: 'Element',
  viewport: 'Viewport',
  reviewTitle: 'Review feedback',
  noItems: 'No feedback yet',
  generatedBy: 'Generated by VibeCheck',
  itemCount: (n: number) => `${n} item${n === 1 ? '' : 's'}`,
} as const

export type Strings = Widen<typeof EN>

const JA: Strings = {
  background: '背景',
  request: 'アップデート内容',
  page: 'ページ',
  element: '要素',
  viewport: 'ビューポート',
  reviewTitle: 'レビュー指摘',
  noItems: '指摘がありません',
  generatedBy: 'VibeCheck で作成',
  itemCount: (n: number) => `${n}件の指摘`,
}

export const STRINGS: Record<Locale, Strings> = { en: EN, ja: JA }

export function stringsFor(locale: Locale): Strings {
  return STRINGS[locale]
}

export function resolveLocale(setting: Locale | 'auto', uiLanguage: string): Locale {
  if (setting !== 'auto') return setting
  return uiLanguage.toLowerCase().startsWith('ja') ? 'ja' : 'en'
}
