import { describe, expect, it } from 'vitest'
import { makeItem, numbered } from './fixtures'
import { buildIssue } from './issue'

const options = { locale: 'en' as const, images: { kind: 'none' as const } }

describe('buildIssue', () => {
  it('uses the requested change as the title for a single item', () => {
    const { title } = buildIssue(numbered([makeItem()]), options)
    expect(title).toBe('Right-align and add thousands separators.')
  })

  it('drops the redundant heading for a single item', () => {
    expect(buildIssue(numbered([makeItem()]), options).body).not.toContain('### #1')
  })

  it('summarises the batch in the title and keeps per-item headings', () => {
    const items = numbered([makeItem({ id: 'a' }), makeItem({ id: 'b' }), makeItem({ id: 'c' })])
    const { title, body } = buildIssue(items, options)
    expect(title).toBe('Review feedback: app.example.com (3 items)')
    expect(body).toContain('### #1')
    expect(body).toContain('### #3')
  })

  it('localises the batch title', () => {
    const items = numbered([makeItem({ id: 'a' }), makeItem({ id: 'b' })])
    expect(buildIssue(items, { ...options, locale: 'ja' }).title).toBe(
      'レビュー指摘: app.example.com (2件の指摘)',
    )
  })

  it('always attributes the issue so readers know where it came from', () => {
    expect(buildIssue(numbered([makeItem()]), options).body).toContain('Generated by VibeCheck')
  })

  it('degrades to a bare title with no items', () => {
    expect(buildIssue([], options).title).toBe('Review feedback')
  })
})
