import type { FeedbackItem, Locale, NumberedItem } from '@/types'
import { stringsFor } from './i18n'
import { itemLabel } from './naming'

export type ImageMode =
  /** No image references at all. */
  | { kind: 'none' }
  /** `![#1](path)` using a local file path — Claude Code and friends can read it. */
  | { kind: 'path'; paths: Record<string, string> }
  /** `![#1](https://…)` inline image. */
  | { kind: 'inline'; urls: Record<string, string> }
  /** `[#1 screenshot](https://…)` link only — for hosts that will not render the image. */
  | { kind: 'link'; urls: Record<string, string> }

export interface MarkdownOptions {
  locale: Locale
  images: ImageMode
  /** Start each item with `### #n …`. Off for single-item output. */
  headings?: boolean
  /** Append a `— Generated by VibeCheck` footer. */
  footer?: boolean
}

/**
 * Wrap a link destination that Markdown would otherwise mis-parse. Absolute
 * paths routinely contain spaces (`/Users/First Last/Downloads/…`), which ends
 * the destination early and breaks the image.
 */
function linkDestination(target: string): string {
  if (!/[\s()]/.test(target)) return target
  return `<${target.replace(/([<>])/g, '\\$1')}>`
}

function imageMarkdown(item: FeedbackItem, seq: number, mode: ImageMode): string | null {
  switch (mode.kind) {
    case 'none':
      return null
    case 'path': {
      const path = mode.paths[item.id]
      return path ? `![#${seq}](${linkDestination(path)})` : null
    }
    case 'inline': {
      const url = mode.urls[item.id]
      return url ? `![#${seq}](${linkDestination(url)})` : null
    }
    case 'link': {
      const url = mode.urls[item.id]
      return url ? `[#${seq} screenshot](${linkDestination(url)})` : null
    }
  }
}

function renderItem(
  item: FeedbackItem,
  seq: number,
  options: MarkdownOptions,
): string {
  const t = stringsFor(options.locale)
  const lines: string[] = []

  if (options.headings !== false) {
    lines.push(`### #${seq} ${itemLabel(item)}`, '')
  }

  if (item.background.trim()) {
    lines.push(`**${t.background}**`, '', item.background.trim(), '')
  }
  if (item.request.trim()) {
    lines.push(`**${t.request}**`, '', item.request.trim(), '')
  }

  const meta: string[] = [`- ${t.page}: ${item.page.url}`]
  if (item.target) {
    meta.push(`- ${t.element}: \`${item.target.selector}\``)
  }
  meta.push(
    `- ${t.viewport}: ${item.page.viewportWidth}×${item.page.viewportHeight} @${item.page.dpr}x`,
  )
  lines.push(...meta, '')

  const image = imageMarkdown(item, seq, options.images)
  if (image) lines.push(image, '')

  return lines.join('\n').trimEnd()
}

/**
 * Render feedback items as Markdown. Each item keeps the number it carries in
 * the panel and in the contact sheet's badge, so a reader can always pair a
 * picture with its text.
 */
export function renderMarkdown(items: NumberedItem[], options: MarkdownOptions): string {
  const t = stringsFor(options.locale)
  if (items.length === 0) return t.noItems

  const blocks = items.map(({ item, seq }) => renderItem(item, seq, options))
  const body = blocks.join('\n\n---\n\n')
  return options.footer ? `${body}\n\n---\n\n_${t.generatedBy}_` : body
}

/** Plain text, no image references — for pasting into a chat as a quick note. */
export function renderPlainText(items: NumberedItem[], locale: Locale): string {
  const t = stringsFor(locale)
  if (items.length === 0) return t.noItems
  return items
    .map(({ item, seq }) => {
      const lines = [`#${seq} ${itemLabel(item)}`]
      if (item.background.trim()) lines.push(`${t.background}: ${item.background.trim()}`)
      if (item.request.trim()) lines.push(`${t.request}: ${item.request.trim()}`)
      lines.push(`${t.page}: ${item.page.url}`)
      return lines.join('\n')
    })
    .join('\n\n')
}

/**
 * Slack reserves `&`, `<` and `>` for its own markup, so feedback like
 * "`<Button>` の余白を詰める" would otherwise vanish into a broken link.
 */
export function escapeSlack(text: string): string {
  return text.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
}

/**
 * Slack renders mrkdwn, not Markdown: `**bold**` and `###` headings come out
 * as literal characters, so the same content needs its own dialect.
 */
export function renderSlackText(items: NumberedItem[], locale: Locale): string {
  const t = stringsFor(locale)
  if (items.length === 0) return t.noItems

  return items
    .map(({ item, seq }) => {
      const e = escapeSlack
      const lines = [`*#${seq}  ${e(itemLabel(item))}*`]
      if (item.background.trim()) lines.push(`*${t.background}*`, e(item.background.trim()))
      if (item.request.trim()) lines.push(`*${t.request}*`, e(item.request.trim()))
      // No `|label` part: the label would be the URL anyway, and a `|` inside
      // the URL would be read as the separator.
      lines.push(`<${e(item.page.url)}>`)
      if (item.target) lines.push(`\`${e(item.target.selector)}\``)
      return lines.join('\n')
    })
    .join('\n\n')
}
