import { describe, expect, it } from 'vitest'
import { makeItem, numbered } from './fixtures'
import { renderMarkdown, renderPlainText, renderSlackText } from './markdown'

const base = { locale: 'en' as const, images: { kind: 'none' as const } }

describe('renderMarkdown', () => {
  it('numbers items by array order', () => {
    const out = renderMarkdown(numbered([makeItem({ id: 'a' }), makeItem({ id: 'b' })]), base)
    expect(out).toContain('### #1')
    expect(out).toContain('### #2')
  })

  it('separates items with a horizontal rule', () => {
    const out = renderMarkdown(numbered([makeItem({ id: 'a' }), makeItem({ id: 'b' })]), base)
    expect(out.split('\n---\n')).toHaveLength(2)
  })

  it('labels the two fields in Japanese when asked', () => {
    const out = renderMarkdown(numbered([makeItem()]), { ...base, locale: 'ja' })
    expect(out).toContain('**背景**')
    expect(out).toContain('**アップデート内容**')
  })

  it('omits an empty field rather than leaving a blank heading', () => {
    const out = renderMarkdown(numbered([makeItem({ background: '   ' })]), base)
    expect(out).not.toContain('**Background**')
    expect(out).toContain('**Requested change**')
  })

  it('includes the element selector so an agent can find the code', () => {
    expect(renderMarkdown(numbered([makeItem()]), base)).toContain('`#totals > .amount`')
  })

  it('omits the element line for comment-only items', () => {
    const out = renderMarkdown(numbered([makeItem({ kind: 'comment', target: undefined })]), base)
    expect(out).not.toContain('Element:')
  })

  it('embeds local paths when exporting for a coding agent', () => {
    const out = renderMarkdown(numbered([makeItem({ id: 'a' })]), {
      ...base,
      images: { kind: 'path', paths: { a: '/Users/me/Downloads/vibecheck/01-x.png' } },
    })
    expect(out).toContain('![#1](/Users/me/Downloads/vibecheck/01-x.png)')
  })

  it('falls back to a link when the host will not render the image', () => {
    const out = renderMarkdown(numbered([makeItem({ id: 'a' })]), {
      ...base,
      images: { kind: 'link', urls: { a: 'https://github.com/o/r/blob/b/a.png' } },
    })
    expect(out).toContain('[#1 screenshot](https://github.com/o/r/blob/b/a.png)')
    expect(out).not.toContain('![#1]')
  })

  it('skips the image reference when the item has no screenshot', () => {
    const out = renderMarkdown(numbered([makeItem({ id: 'a', kind: 'comment', shotKey: undefined })]), {
      ...base,
      images: { kind: 'path', paths: {} },
    })
    expect(out).not.toContain('![')
  })

  it('reports emptiness instead of returning a blank string', () => {
    expect(renderMarkdown([], base)).toBe('No feedback yet')
  })

  it('adds the footer only when requested', () => {
    expect(renderMarkdown(numbered([makeItem()]), base)).not.toContain('VibeCheck')
    expect(renderMarkdown(numbered([makeItem()]), { ...base, footer: true })).toContain(
      'Generated by VibeCheck',
    )
  })
})

describe('renderPlainText', () => {
  it('keeps one compact block per item', () => {
    const out = renderPlainText(numbered([makeItem({ id: 'a' }), makeItem({ id: 'b' })]), 'en')
    expect(out).toContain('#1 Right-align and add thousands separators.')
    expect(out).toContain('#2 Right-align and add thousands separators.')
    expect(out).not.toContain('![')
  })
})

describe('renderSlackText', () => {
  it('uses mrkdwn bold, not Markdown bold', () => {
    const out = renderSlackText(numbered([makeItem()]), 'en')
    expect(out).toContain('*Background*')
    expect(out).not.toContain('**')
  })

  it('never emits Markdown headings, which Slack shows literally', () => {
    expect(renderSlackText(numbered([makeItem()]), 'en')).not.toContain('###')
  })

  it('wraps the URL in Slack link syntax', () => {
    expect(renderSlackText(numbered([makeItem()]), 'en')).toContain(
      '<https://app.example.com/dashboard|https://app.example.com/dashboard>',
    )
  })

  it('numbers items to match the contact sheet badges', () => {
    const out = renderSlackText(numbered([makeItem({ id: 'a' }), makeItem({ id: 'b' })]), 'en')
    expect(out).toContain('*#1  ')
    expect(out).toContain('*#2  ')
  })

  it('reports emptiness rather than posting a blank message', () => {
    expect(renderSlackText([], 'ja')).toBe('指摘がありません')
  })
})

describe('explicit numbering', () => {
  it('uses the number it is handed, not the array position', () => {
    // The panel hides handled items, so a batch can be #2 and #4 with a gap.
    const out = renderMarkdown(
      [
        { item: makeItem({ id: 'a' }), seq: 2 },
        { item: makeItem({ id: 'b' }), seq: 4 },
      ],
      base,
    )
    expect(out).toContain('### #2')
    expect(out).toContain('### #4')
    expect(out).not.toContain('### #1')
  })

  it('keeps the image reference on the same number as its text', () => {
    const out = renderMarkdown([{ item: makeItem({ id: 'a' }), seq: 3 }], {
      ...base,
      images: { kind: 'path', paths: { a: '/tmp/03-x.png' } },
    })
    expect(out).toContain('### #3')
    expect(out).toContain('![#3](/tmp/03-x.png)')
  })

  it('carries the same numbers into the Slack and plain-text dialects', () => {
    const batch = [{ item: makeItem({ id: 'a' }), seq: 5 }]
    expect(renderSlackText(batch, 'en')).toContain('*#5  ')
    expect(renderPlainText(batch, 'en')).toContain('#5 ')
  })
})
