import type { FeedbackItem, Locale } from '@/types'
import { stringsFor } from './i18n'
import { itemLabel } from './naming'

export type ImageMode =
  /** No image references at all. */
  | { kind: 'none' }
  /** `![#1](path)` using a local file path — Claude Code and friends can read it. */
  | { kind: 'path'; paths: Record<string, string> }
  /** `![#1](https://…)` inline image. */
  | { kind: 'inline'; urls: Record<string, string> }
  /** `[#1 screenshot](https://…)` link only — for hosts that will not render the image. */
  | { kind: 'link'; urls: Record<string, string> }

export interface MarkdownOptions {
  locale: Locale
  images: ImageMode
  /** Start each item with `### #n …`. Off for single-item output. */
  headings?: boolean
  /** Append a `— Generated by VibeCheck` footer. */
  footer?: boolean
}

function imageMarkdown(item: FeedbackItem, seq: number, mode: ImageMode): string | null {
  switch (mode.kind) {
    case 'none':
      return null
    case 'path': {
      const path = mode.paths[item.id]
      return path ? `![#${seq}](${path})` : null
    }
    case 'inline': {
      const url = mode.urls[item.id]
      return url ? `![#${seq}](${url})` : null
    }
    case 'link': {
      const url = mode.urls[item.id]
      return url ? `[#${seq} screenshot](${url})` : null
    }
  }
}

function renderItem(
  item: FeedbackItem,
  seq: number,
  options: MarkdownOptions,
): string {
  const t = stringsFor(options.locale)
  const lines: string[] = []

  if (options.headings !== false) {
    lines.push(`### #${seq} ${itemLabel(item)}`, '')
  }

  if (item.background.trim()) {
    lines.push(`**${t.background}**`, '', item.background.trim(), '')
  }
  if (item.request.trim()) {
    lines.push(`**${t.request}**`, '', item.request.trim(), '')
  }

  const meta: string[] = [`- ${t.page}: ${item.page.url}`]
  if (item.target) {
    meta.push(`- ${t.element}: \`${item.target.selector}\``)
  }
  meta.push(
    `- ${t.viewport}: ${item.page.viewportWidth}×${item.page.viewportHeight} @${item.page.dpr}x`,
  )
  lines.push(...meta, '')

  const image = imageMarkdown(item, seq, options.images)
  if (image) lines.push(image, '')

  return lines.join('\n').trimEnd()
}

/**
 * Render feedback items as Markdown. Sequence numbers come from array order and
 * match the badges burned into the contact sheet, so a reader can always pair
 * a picture with its text.
 */
export function renderMarkdown(items: FeedbackItem[], options: MarkdownOptions): string {
  const t = stringsFor(options.locale)
  if (items.length === 0) return t.noItems

  const blocks = items.map((item, index) => renderItem(item, index + 1, options))
  const body = blocks.join('\n\n---\n\n')
  return options.footer ? `${body}\n\n---\n\n_${t.generatedBy}_` : body
}

/** Plain text, no image references — for pasting into a chat as a quick note. */
export function renderPlainText(items: FeedbackItem[], locale: Locale): string {
  const t = stringsFor(locale)
  if (items.length === 0) return t.noItems
  return items
    .map((item, index) => {
      const lines = [`#${index + 1} ${itemLabel(item)}`]
      if (item.background.trim()) lines.push(`${t.background}: ${item.background.trim()}`)
      if (item.request.trim()) lines.push(`${t.request}: ${item.request.trim()}`)
      lines.push(`${t.page}: ${item.page.url}`)
      return lines.join('\n')
    })
    .join('\n\n')
}

/**
 * Slack renders mrkdwn, not Markdown: `**bold**` and `###` headings come out
 * as literal characters, so the same content needs its own dialect.
 */
export function renderSlackText(items: FeedbackItem[], locale: Locale): string {
  const t = stringsFor(locale)
  if (items.length === 0) return t.noItems

  return items
    .map((item, index) => {
      const lines = [`*#${index + 1}  ${itemLabel(item)}*`]
      if (item.background.trim()) lines.push(`*${t.background}*`, item.background.trim())
      if (item.request.trim()) lines.push(`*${t.request}*`, item.request.trim())
      lines.push(`<${item.page.url}|${item.page.url}>`)
      if (item.target) lines.push(`\`${item.target.selector}\``)
      return lines.join('\n')
    })
    .join('\n\n')
}
